service: musingsole

plugins:
  - serverless-python-requirements
provider:
  name: aws
  stage: prod
  runtime: python3.8
  region: us-east-1
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: "arn:aws:s3:::musingsole/*"

functions:
  musingsole:
    name: musingsole
    handler: blog.lambda_handler
    memorySize: 128
    timeout: 30
    events:
      - http:
          path: /entry/{entry_title}
          method: get
      - http:
          path: /asset/{asset_name}
          method: get
          contentHandling: CONVERT_TO_BINARY
      - http:
          path: /
          method: get

custom:
  pythonRequirements:
    dockerizePip: non-linux
    noDeploy: []

